'use client';
import Link from 'next/link';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Bell, CalendarBlank, Check, Clock, DoorOpen, GearSix, Tray, Package, Plugs, Plus, QrCode, ShieldCheck, Users, Wrench, X } from '@phosphor-icons/react';
import QRCode from 'qrcode';
import type { Arrival, Expected, Notification, Principal, SiteSettings, Versioned, Action } from '@doorsignal/core/types';
import { Brand } from './Brand';
import { api } from './api';
import { StartDemo } from './StartDemo';
import { Integrations } from './Integrations';

type View = 'today' | 'arrivals' | 'deliveries' | 'workflows' | 'integrations' | 'settings';
const nav = [{ id: 'today', label: 'Arrival inbox', icon: Tray }, { id: 'arrivals', label: 'Expected arrivals', icon: CalendarBlank }, { id: 'deliveries', label: 'Deliveries', icon: Package }, { id: 'workflows', label: 'Workflows', icon: ArrowUpRight }, { id: 'integrations', label: 'Integrations', icon: Plugs }, { id: 'settings', label: 'Settings', icon: GearSix }] as const;
const stateLabel = { needs_review: 'Needs review', waiting: 'Waiting for host', acknowledged: 'Host on the way', received: 'Ready to collect', resolved: 'Complete' };
const kindIcon = { GUEST: Users, DELIVERY: Package, SERVICE: Wrench, UNMATCHED: DoorOpen };
const time = (date: string) => new Date(date).toLocaleTimeString('en', { hour: 'numeric', minute: '2-digit' });
const date = (value: string) => new Date(value).toLocaleDateString('en', { month: 'short', day: 'numeric' });
function Badge({ arrival }: { arrival: Arrival }) { return <span className={`badge ${arrival.status}`}>{stateLabel[arrival.status]}</span>; }
function Dialog({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { ref.current?.showModal(); }, []);
  return <dialog ref={ref} onCancel={onClose} aria-label={title}><header className="dialog-header"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={20} /></button></header>{children}</dialog>;
}
function Sign({ link, onClose }: { link: string; onClose: () => void }) {
  const [qr, setQr] = useState('');
  useEffect(() => { QRCode.toDataURL(link, { width: 600, margin: 4, color: { dark: '#172221', light: '#ffffff' }, errorCorrectionLevel: 'M' }).then(setQr); }, [link]);
  return <Dialog title="Visitor check-in sign" onClose={onClose}><div className="printable"><Brand /><p className="eyebrow">Welcome to DoorSignal House</p><h3>Let your host<br />know you’re here.</h3>{qr ? <img width={260} height={260} src={qr} alt="Scannable QR code for this site's visitor check-in" /> : <p role="status">Generating your QR code…</p>}<p>Scan to check in.<br />Your host’s response appears on your phone.</p><small>This sign’s link expires in 24 hours.<br />Generate a fresh sign for the next day.</small></div><div className="dialog-actions"><a className="button" href={link} target="_blank" rel="noreferrer">Open visitor page <ArrowUpRight /></a><button className="button primary" onClick={() => window.print()}>Print sign</button></div></Dialog>;
}
export function Dashboard({ view }: { view: View }) {
  const [session, setSession] = useState<{ principal: Principal; settings: SiteSettings } | null>(null);
  const [cases, setCases] = useState<Versioned<Arrival>[]>([]), [expected, setExpected] = useState<Versioned<Expected>[]>([]), [notifications, setNotifications] = useState<Notification[]>([]);
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [busy, setBusy] = useState(''), [notice, setNotice] = useState('');
  const [selected, setSelected] = useState(''), [filter, setFilter] = useState('open'), [sign, setSign] = useState(''), [showExpected, setShowExpected] = useState(false), [showNotifications, setShowNotifications] = useState(false), [deleting, setDeleting] = useState(false);
  const [visitorLink, setVisitorLink] = useState('');
  const refresh = useCallback(async () => {
    try {
      const [session, arrivals, scheduled, messages] = await Promise.all([api('/session'), api('/cases'), api('/v1/expected-arrivals'), api('/notifications')]);
      setSession(session); setCases(arrivals.cases); setExpected(scheduled.data); setNotifications(messages.notifications); setError('');
      setSelected(previous => previous || arrivals.cases[0]?.id || '');
    } catch (error) { setError((error as Error).message); } finally { setLoading(false); }
  }, []);
  useEffect(() => { void refresh(); const interval = setInterval(() => { if (!document.hidden) void refresh(); }, 8000); return () => clearInterval(interval); }, [refresh]);
  useEffect(() => { const value = new URLSearchParams(window.location.search).get('case'); if (value) setSelected(value); }, []);
  const run = async (name: string, task: () => Promise<unknown>) => {
    setBusy(name); setError(''); setNotice(''); try { await task(); await refresh(); } catch (error) { setError((error as Error).message); } finally { setBusy(''); }
  };
  const runStory = (story: string) => run(story, async () => {
    const result = await api('/simulate', { method: 'POST', body: JSON.stringify({ story }) }); setSelected(result.caseId); setFilter('open'); setVisitorLink(result.visitorPath || ''); setNotice(`${story[0].toUpperCase() + story.slice(1)} replay created. Its records are saved in your isolated workspace.`);
  });
  const openSign = (expectedId?: string) => run('sign', async () => { const result = await api('/checkin/link', { method: 'POST', body: JSON.stringify({ expectedId }) }); setSign(result.url); });
  const active = cases.filter(x => x.status !== 'resolved');
  const visibleCases = cases.filter(x => view !== 'deliveries' || x.kind === 'DELIVERY').filter(x => filter === 'all' || (filter === 'open' ? x.status !== 'resolved' : x.status === 'resolved'));
  const chosen = cases.find(x => x.id === selected);
  const action = (action: Action) => chosen && run(action, async () => { await api(`/cases/${chosen.id}/action`, { method: 'POST', body: JSON.stringify({ action, version: chosen.version }) }); setNotice('Action saved. The visitor and other hosts can see the updated status.'); });
  if (loading) return <main id="main" className="loading-page"><Brand /><p role="status">Opening your arrival inbox…</p><div className="loading-line" /></main>;
  if (!session) return <main id="main" className="welcome-panel"><Brand /><h1>A place for every arrival.</h1><p>Try the guest, delivery, and service stories in your own isolated demo workspace.</p><StartDemo /><a className="text-link" href="/api/auth/login">Operator sign in ↗</a>{error && <p className="quiet">{error}</p>}</main>;
  const pageTitle = nav.find(x => x.id === view)!.label;
  return <div className="workspace"><aside className="sidebar"><Link href="/" aria-label="DoorSignal home"><Brand /></Link><div className="site-switch"><span className="site-monogram">D</span><div><strong>{session.settings.name}</strong><small>{session.principal.mode === 'replay' ? 'Judge workspace' : 'Operator workspace'}</small></div></div><nav aria-label="Workspace">{nav.map(({ id, label, icon: Icon }) => <Link key={id} href={`/${id}`} aria-current={view === id ? 'page' : undefined}><Icon size={20} weight={view === id ? 'fill' : 'regular'} /><span>{label}</span>{id === 'today' && active.length > 0 && <span className="nav-count">{active.length}</span>}</Link>)}</nav><div className="sidebar-bottom"><div className="care-note"><ShieldCheck size={22} /><p>People provide the welcome.<br />DoorSignal keeps the handoff clear.</p></div><button className="account-button" onClick={() => run('logout', async () => { await api('/auth/logout', { method: 'POST' }); window.location.assign('/'); })}><span className="avatar">{session.principal.mode === 'replay' ? 'J' : 'H'}</span><span>{session.principal.mode === 'replay' ? 'Judge demo' : 'Host'}<small>Leave workspace</small></span><ArrowUpRight /></button></div></aside>
    <div className="workspace-main"><header className="topbar"><div><span className="quiet">Workspace</span><span className="crumb">/</span><span>{pageTitle}</span></div><div className="topbar-actions"><span className={`mode-badge ${session.principal.mode}`}><span className="dot" />{session.principal.mode === 'replay' ? 'Demo replay' : 'Live playground'}</span><button className="icon-button" onClick={() => setShowNotifications(true)} aria-label={`Notifications, ${notifications.length} saved`}><Bell size={21} />{notifications.length > 0 && <span className="notification-dot" />}</button></div></header>
      <main id="main" className="dashboard-content"><div className="page-heading"><div><p className="eyebrow">{view === 'today' ? 'A good welcome starts here' : 'DoorSignal House'}</p><h1>{view === 'today' ? 'At your door.' : pageTitle}</h1><p>{view === 'today' ? 'Every arrival has a next step. Make it a clear one.' : view === 'deliveries' ? 'From the front desk to the right hands.' : view === 'arrivals' ? 'Give your team context before the doorbell rings.' : view === 'integrations' ? 'Connect the services that support your arrivals.' : view === 'settings' ? 'A few details that keep your workspace running.' : 'Simple rules, with people in control.'}</p></div><div className="heading-actions"><button className="button" disabled={!!busy} onClick={() => openSign()}><QrCode size={19} />Check-in sign</button><button className="button primary" onClick={() => setShowExpected(true)}><Plus size={18} />Expected arrival</button></div></div>
      {session.principal.mode === 'replay' && <section className="replay-bar" aria-label="Demo controls"><div><strong>Try an arrival</strong><span>Fictional records · no live camera or external email</span></div><div className="replay-buttons">{(['guest', 'delivery', 'service', 'unmatched'] as const).map(story => <button key={story} disabled={!!busy} onClick={() => runStory(story)}>{busy === story ? 'Creating…' : story === 'unmatched' ? 'Unmatched arrival' : `${story[0].toUpperCase() + story.slice(1)}`}</button>)}</div></section>}
      {error && <div className="alert error" role="alert"><span>{error}</span><button onClick={() => void refresh()}>Retry</button></div>}{notice && <div className="alert success" role="status">{notice}<button aria-label="Dismiss message" onClick={() => setNotice('')}><X /></button></div>}
      {(view === 'today' || view === 'deliveries') && <><div className="summary-strip"><div><span className="stat-marker orange" /><span>Needs attention</span><strong>{active.filter(x => x.status === 'needs_review' || x.status === 'waiting').length}</strong></div><div><span className="stat-marker teal" /><span>Host on the way</span><strong>{active.filter(x => x.status === 'acknowledged').length}</strong></div><div><span className="stat-marker amber" /><span>Ready to collect</span><strong>{active.filter(x => x.status === 'received').length}</strong></div><div><Check size={16} /><span>Completed</span><strong>{cases.length - active.length}</strong></div></div>
      <section className={`inbox-layout ${chosen ? 'has-selection' : ''}`}><div className="inbox-list"><div className="list-toolbar"><div className="tabs" aria-label="Filter arrivals">{['open', 'all', 'closed'].map(value => <button key={value} aria-pressed={filter === value} onClick={() => setFilter(value)}>{value === 'open' ? 'Open' : value === 'all' ? 'All arrivals' : 'Completed'}</button>)}</div><span className="quiet">{visibleCases.length}</span></div>{visibleCases.length === 0 ? <div className="empty-state"><DoorOpen size={36} weight="light" /><h3>A little quiet at the door.</h3><p>{session.principal.mode === 'replay' ? 'Choose a demo story above to bring an arrival into your inbox.' : 'Connect Ring in Integrations and import recent events to get started.'}</p></div> : visibleCases.map(arrival => { const Icon = kindIcon[arrival.kind]; return <button className={`arrival-row ${selected === arrival.id ? 'selected' : ''}`} key={arrival.id} onClick={() => setSelected(arrival.id)} aria-pressed={selected === arrival.id}><span className={`arrival-icon ${arrival.kind.toLowerCase()}`}><Icon size={22} /></span><span className="arrival-row-main"><span className="row-title"><strong>{arrival.title}</strong><time dateTime={arrival.occurredAt}>{time(arrival.occurredAt)}</time></span><span className="row-subtitle">{arrival.owner} <span>·</span> {arrival.kind === 'UNMATCHED' ? 'Human review' : arrival.kind[0] + arrival.kind.slice(1).toLowerCase()}</span><Badge arrival={arrival} /></span></button>; })}<div className="list-footnote"><ShieldCheck size={15} /> No facial recognition</div></div>
      <section className="case-detail" aria-label="Arrival details">{chosen ? <><div className="detail-top"><button className="back-list" onClick={() => setSelected('')}>← Back to arrivals</button><span className="eyebrow">{chosen.source === 'demo_replay' ? 'Demo replay' : chosen.source === 'checkin' ? 'Visitor check-in' : 'Ring event'} <span className="quiet">/</span> {date(chosen.occurredAt)}</span><Badge arrival={chosen} /></div><div className="detail-title"><span className={`arrival-icon large ${chosen.kind.toLowerCase()}`}>{(() => { const Icon = kindIcon[chosen.kind]; return <Icon size={30} />; })()}</span><h2>{chosen.title}</h2><p>{chosen.reason}</p></div><dl className="case-facts"><div><dt>Owner</dt><dd><span className="avatar small">{chosen.owner[0]}</span>{chosen.owner}</dd></div><div><dt>Arrival context</dt><dd>{chosen.match === 'tentative' ? 'Suggested · confirm with a person' : chosen.match === 'checkin' ? 'Visitor check-in received' : chosen.match === 'human' ? 'Confirmed by a host' : 'Needs a person’s review'}</dd></div><div><dt>Scene information</dt><dd>{chosen.scene.status === 'unknown' ? 'Unknown' : [chosen.scene.personPresent === true && 'Person visible', chosen.scene.packagePresent === true && 'Package visible', chosen.scene.vehiclePresent === true && 'Vehicle visible'].filter(Boolean).join(' · ') || 'No positive scene signals'}</dd></div></dl>
      {chosen.status !== 'resolved' && <div className="case-actions">{['waiting','needs_review'].includes(chosen.status) && <button className="button primary" disabled={!!busy} onClick={() => action('ACKNOWLEDGE')}><Check size={17} />I’m on my way</button>}{chosen.kind === 'DELIVERY' && <button className="button primary" disabled={!!busy} onClick={() => action(chosen.status === 'received' ? 'COLLECTED' : 'RECEIVED')}>{chosen.status === 'received' ? 'Mark collected' : 'Mark received'}</button>}{chosen.expectedId && chosen.match === 'tentative' && <button className="button" disabled={!!busy} onClick={() => action('CONFIRM')}>Confirm match</button>}<button className="button" disabled={!!busy} onClick={() => action('DISMISS')}>Close arrival</button><details className="action-menu"><summary>More actions</summary><button disabled={!!busy} onClick={() => action('NOTIFY')}>Notify host</button><button disabled={!!busy} onClick={() => action('ESCALATE')}>Escalate for review</button>{chosen.expectedId && <button disabled={!!busy} onClick={() => action('NOT_A_MATCH')}>Not a match</button>}</details></div>}
      {chosen.expectedId && !chosen.checkinId && <div className="checkin-prompt"><QrCode size={22} /><div><strong>Complete the visitor’s side</strong><p>Use the check-in page in another tab or on a phone.</p></div><button className="text-link" disabled={!!busy} onClick={() => openSign(chosen.expectedId)}>Open sign ↗</button></div>}
      {visitorLink && chosen.kind === 'GUEST' && !chosen.checkinId && <a className="visitor-direct" href={visitorLink} target="_blank" rel="noreferrer">Open Maya’s visitor check-in <ArrowUpRight size={16} /></a>}
      <div className="activity-heading"><h3>Activity</h3><span>Saved history</span></div><ol className="activity-list">{chosen.timeline.map((entry, index) => <li key={`${entry.at}-${index}`}><span className={`activity-node ${index === chosen.timeline.length-1 ? 'latest' : ''}`} /><div><strong>{entry.actor}</strong><p>{entry.text}</p></div><time dateTime={entry.at}>{time(entry.at)}</time></li>)}</ol><div className="detail-note"><ShieldCheck size={16} /><p>{chosen.scene.reason}</p></div></> : <div className="empty-state"><Tray size={38} weight="light" /><h3>The next step lives here.</h3><p>Select an arrival to see its context, owner, and activity.</p></div>}</section></section></>}
      {view === 'arrivals' && <section className="table-panel"><div className="table-heading"><h2>On the calendar</h2><span>{expected.length} expected</span></div>{!expected.length ? <div className="empty-state"><CalendarBlank size={36} /><h3>Give arrivals a little context.</h3><p>Add your next guest, delivery, or service visit.</p></div> : <div className="table-scroll"><table><thead><tr><th>Expected arrival</th><th>Owner</th><th>Window</th><th>Check-in</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{expected.map(row => <tr key={row.id}><td><strong>{row.name}</strong><small>{row.kind[0] + row.kind.slice(1).toLowerCase()}</small></td><td>{row.host}</td><td>{date(row.startsAt)}<small>{time(row.startsAt)} – {time(row.endsAt)}</small></td><td><button className="text-link" onClick={() => openSign(row.id)}>Create invitation ↗</button></td><td><button className="icon-button" aria-label={`Remove expected arrival ${row.name}`} disabled={!!busy} onClick={() => run('remove', () => api(`/v1/expected-arrivals/${row.id}`, { method: 'DELETE' }))}><X size={17} /></button></td></tr>)}</tbody></table></div>}</section>}
      {view === 'workflows' && <section className="workflow-list">{[{ icon: Users, title: 'Welcome a guest', steps: ['Door event arrives', 'Compare expected visit window', 'Visitor checks in', 'Host acknowledges', 'Close the visit'], note: 'Timing suggests a visit. An invitation or a host provides confirmation.' }, { icon: Package, title: 'Keep track of a delivery', steps: ['Delivery arrival', 'Host confirms context', 'Mark received', 'Keep visible at reception', 'Mark collected'], note: 'Receipt and collection are separate states. A delivery stays open between them.' }, { icon: Wrench, title: 'Review a service visit', steps: ['Compare service window', 'Show the proposed context', 'Ask a person to confirm', 'Escalate if unmatched', 'Close after review'], note: 'Unmatched arrivals require human review. The model cannot grant access or take action.' }].map(({ icon: Icon, title, steps, note }) => <article key={title}><header><Icon size={27} /><h2>{title}</h2><span className="badge acknowledged">Enforced in the app</span></header><ol>{steps.map(step => <li key={step}>{step}</li>)}</ol><p>{note}</p></article>)}</section>}
      {view === 'integrations' && <Integrations mode={session.principal.mode} onError={setError} />}
      {view === 'settings' && <section className="settings-panel"><form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void run('settings', async () => { await api('/settings', { method: 'PUT', body: JSON.stringify({ name: form.get('name'), timeZone: form.get('timeZone'), retentionDays: 7, emailEnabled: form.get('emailEnabled') === 'on' }) }); setNotice('Workspace settings saved.'); }); }}><h2>Workspace details</h2><label>Workspace name<input name="name" defaultValue={session.settings.name} required maxLength={80} /></label><label>Time zone<input name="timeZone" defaultValue={session.settings.timeZone} required /><small>Use an IANA time zone, such as America/New_York.</small></label><label className="checkbox-label"><input name="emailEnabled" type="checkbox" defaultChecked={session.settings.emailEnabled} disabled={session.principal.mode === 'replay'} /> Send email to the configured host recipient</label><p className="quiet">Email is disabled in the public demo. Configure a verified recipient in Integrations before enabling it for live events.</p><button className="button primary" disabled={!!busy}>Save settings</button></form><div className="retention-panel"><ShieldCheck size={26} /><h2>Your data stays yours.</h2><p>Live operational records expire after 7 days. Demo records expire after 24 hours. Future expected arrivals remain until their window ends, plus one day. Camera images are never saved by DoorSignal.</p><p>Expired records are hidden immediately; DynamoDB removes them asynchronously. Deleting site data removes active records. Logs contain no camera images or visitor names.</p><button className="button danger" onClick={() => setDeleting(true)}>Delete this workspace’s data</button></div></section>}
      <footer className="workspace-footer"><span><span className="dot" />{session.principal.mode === 'replay' ? 'Your demo is isolated from live accounts.' : 'Connected services are managed in Integrations.'}</span><a href="/privacy">Privacy & data</a></footer>
    </main></div>
    {sign && <Sign link={sign} onClose={() => setSign('')} />}
    {showExpected && <Dialog title="Expect an arrival" onClose={() => setShowExpected(false)}><form className="dialog-form" onSubmit={event => { event.preventDefault(); const values = new FormData(event.currentTarget); void run('expected', async () => { await api('/v1/expected-arrivals', { method: 'POST', body: JSON.stringify({ name: values.get('name'), host: values.get('host'), kind: values.get('kind'), startsAt: new Date(values.get('startsAt') as string).toISOString(), endsAt: new Date(values.get('endsAt') as string).toISOString(), note: values.get('note') }) }); setShowExpected(false); setNotice('Expected arrival saved. You can create its check-in invitation from Expected arrivals.'); }); }}><label>Name or delivery description<input name="name" required maxLength={80} placeholder="Maya Chen" autoFocus /></label><div className="form-row"><label>Arrival type<select name="kind"><option value="GUEST">Guest</option><option value="DELIVERY">Delivery</option><option value="SERVICE">Service</option></select></label><label>Host or owner<input name="host" required maxLength={80} placeholder="Alex Morgan" /></label></div><div className="form-row"><label>Window starts<input type="datetime-local" name="startsAt" required /></label><label>Window ends<input type="datetime-local" name="endsAt" required /></label></div><label>Note <span className="quiet">(optional)</span><textarea name="note" maxLength={240} rows={2} /></label><p className="quiet">A schedule provides context. It does not establish a visitor’s identity.</p>{error && <p className="error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" className="button" onClick={() => setShowExpected(false)}>Cancel</button><button className="button primary" disabled={!!busy}>{busy ? 'Saving…' : 'Save arrival'}</button></div></form></Dialog>}
    {showNotifications && <Dialog title="Notifications" onClose={() => setShowNotifications(false)}><div className="notification-list">{!notifications.length ? <p className="empty-state">No notifications yet.</p> : notifications.map((notification, i) => <article key={`${notification.id}-${i}`}><Bell size={19} /><div><strong>{notification.title}</strong><p>{notification.channel === 'in_app' ? 'Saved in-app' : notification.state === 'sent' ? 'Accepted by SES · inbox delivery not confirmed' : `Email ${notification.state}`}</p>{notification.error && <p className="error">{notification.error}</p>}<time>{time(notification.createdAt)}</time></div><span className={`badge ${notification.state === 'failed' ? 'needs_review' : 'acknowledged'}`}>{notification.state}</span></article>)}</div></Dialog>}
    {deleting && <Dialog title="Delete workspace data" onClose={() => setDeleting(false)}><form className="dialog-form" onSubmit={event => { event.preventDefault(); const value = new FormData(event.currentTarget).get('confirmation'); void run('delete', async () => { await api('/data', { method: 'DELETE', body: JSON.stringify({ confirmation: value }) }); setDeleting(false); setSelected(''); setNotice('The active records in this workspace were deleted.'); }); }}><p>This deletes this workspace’s arrivals, check-ins, notifications, actions, and expected visits.</p><label>Type DELETE SITE DATA to continue<input name="confirmation" required pattern="DELETE SITE DATA" autoComplete="off" /></label><button className="button danger" disabled={!!busy}>Delete site data</button></form></Dialog>}
  </div>;
}
