'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Bell, Code, DoorOpen, Envelope, Play, Stop } from '@phosphor-icons/react';
import { api } from './api';
type Device = { id: string; name: string; status: string; capabilities: Record<string, unknown> };
export function Integrations({ mode, onError }: { mode: string; onError: (error: string) => void }) {
  const [state, setState] = useState<any>(null), [devices, setDevices] = useState<Device[]>([]), [busy, setBusy] = useState(false), [key, setKey] = useState(''), [notice, setNotice] = useState(''), [evidence, setEvidence] = useState<any[]>([]);
  const load = useCallback(async () => { const [value, proof] = await Promise.all([api('/integrations'), api('/evidence')]); setState(value); setEvidence(proof.evidence); if (mode === 'live' && value.ring === 'connected') { const result = await api('/ring/devices'); setDevices(result.devices); } }, [mode]);
  useEffect(() => { load().catch(error => onError(error.message)); }, [load, onError]);
  const run = async (task: () => Promise<void>) => { setBusy(true); onError(''); setNotice(''); try { await task(); await load(); } catch (error) { onError((error as Error).message); } finally { setBusy(false); } };
  if (!state) return <p role="status">Checking connected services…</p>;
  return <div className="integrations-grid"><section className="integration-card ring-card"><div className="integration-title"><span className="integration-icon"><DoorOpen size={27} /></span><div><h2>Ring playground</h2><p>Door events, device status, and live video</p></div><span className={`badge ${state.ring === 'connected' ? 'acknowledged' : 'needs_review'}`}>{state.ring === 'connected' ? 'Connected' : 'Reconnect'}</span></div><p>Connect a token from the official Ring playground. Tokens last about 30 minutes. Live calls go through the DoorSignal server.</p>{mode === 'replay' ? <div className="inline-note">Live Ring credentials are available only to signed-in operators. This judge workspace uses labeled replay events.</div> : <><form className="inline-form" onSubmit={event => { event.preventDefault(); const form = event.currentTarget; const token = new FormData(form).get('token'); void run(async () => { const result = await api('/ring/connect', { method: 'POST', body: JSON.stringify({ token }) }); setDevices(result.devices); form.reset(); setNotice('Ring account and devices verified.'); }); }}><label>Playground access token<input type="password" autoComplete="off" name="token" minLength={20} required placeholder="Paste the current token" /></label><button className="button primary" disabled={busy}>Connect</button></form><div className="integration-links"><a className="text-link" href="https://developer.amazon.com/ring/console/playground" target="_blank" rel="noreferrer">Open official playground <ArrowUpRight size={16} /></a>{state.ring === 'connected' && <button className="text-link" disabled={busy} onClick={() => run(async () => { await api('/ring/disconnect', { method: 'POST' }); setDevices([]); })}>Disconnect</button>}</div>{state.expiresAt && <p className="quiet">Reconnect by {new Date(state.expiresAt).toLocaleTimeString()}.</p>}{devices.map(device => <div className="device-panel" key={device.id}><header><div><strong>{device.name}</strong><small>{device.status === 'online' ? 'Online' : device.status === 'offline' ? 'Offline' : 'Status unknown'}</small></div><button className="button" disabled={busy} onClick={() => run(async () => { const result = await api(`/ring/devices/${encodeURIComponent(device.id)}/history`, { method: 'POST' }); setNotice(`${result.retrieved} recent Ring events retrieved; ${result.accepted} new events accepted. Processing: ${result.processing}.`); })}>Import recent events</button></header><LiveVideo device={device} /></div>)}</>}</section>
    <section className="integration-card"><div className="integration-title"><span className="integration-icon"><Code size={25} /></span><div><h2>Expected-arrivals API</h2><p>Bring your own source of visit context</p></div></div><p>Create expected arrivals through an authenticated, site-scoped API. Keys can manage expected arrivals only.</p><code className="endpoint">POST /api/v1/expected-arrivals</code>{mode === 'live' ? <><button className="button" disabled={busy} onClick={() => run(async () => { const result = await api('/integrations/key', { method: 'POST' }); setKey(result.key); })}>{state.expectedApi === 'configured' ? 'Replace integration key' : 'Create integration key'}</button>{key && <div className="key-output"><p>Copy this key now. Creating another key revokes this one.</p><textarea readOnly value={key} aria-label="New integration API key" /><button className="text-link" onClick={() => navigator.clipboard.writeText(key).then(() => setNotice('Key copied. Keep it private.'))}>Copy key</button></div>}</> : <p className="inline-note">Create and manage demo arrivals in Expected arrivals. Live API keys are hidden from the public demo.</p>}</section>
    <section className="integration-card"><div className="integration-title"><span className="integration-icon"><Bell size={25} /></span><div><h2>In-app notifications</h2><p>A saved handoff for every arrival</p></div><span className="badge acknowledged">Enabled</span></div><p>Notifications appear in this workspace and persist with the arrival. The notification panel shows the actual saved state.</p><p className="quiet">Storage: {state.storage}</p></section>
    <section className="integration-card"><div className="integration-title"><span className="integration-icon"><Envelope size={25} /></span><div><h2>Amazon SES</h2><p>Email the configured host</p></div><span className={`badge ${state.email === 'configured' ? 'acknowledged' : 'neutral'}`}>{state.email === 'configured' ? 'Configured' : mode === 'replay' ? 'Off in demo' : 'Not configured'}</span></div><p>Queued, failed, and SES-accepted requests are tracked separately. Opening an email link never changes an arrival.</p>{mode === 'live' && <form onSubmit={event => { event.preventDefault(); const email = new FormData(event.currentTarget).get('email'); void run(async () => { await api('/integrations/email', { method: 'POST', body: JSON.stringify({ email }) }); setNotice('Recipient configured. Verify it in SES and enable email in Settings.'); }); }}><label>Approved notification recipient<input name="email" type="email" required placeholder="host@example.com" /></label><small>During SES sandbox use, verify both the sender and recipient in AWS before enabling email.</small><button className="button" disabled={busy}>Save recipient</button></form>}</section>
    <section className="integration-card evidence-card"><div className="integration-title"><div><h2>Integration evidence</h2><p>Measurements from this workspace’s actual calls</p></div><button className="button" onClick={() => run(async () => {})} disabled={busy}>Refresh</button></div>{evidence.length ? <div className="table-scroll"><table><thead><tr><th>Service</th><th>Request</th><th>Result</th><th>Time</th></tr></thead><tbody>{evidence.map((entry, index) => <tr key={index}><td>{entry.service}</td><td><code>{entry.method} {entry.path || entry.model}</code></td><td>{entry.status}</td><td>{entry.durationMs} ms</td></tr>)}</tbody></table></div> : <div className="inline-note">No live calls recorded in this workspace. Demo replay does not count as Ring or Bedrock evidence.</div>}<p className="quiet">Bedrock assistance: {state.bedrock}. Availability is reported per request; enabling a service does not prove a successful invocation.</p></section>{notice && <p className="alert success integration-notice" role="status">{notice}</p>}</div>;
}
function LiveVideo({ device }: { device: Device }) {
  const video = useRef<HTMLVideoElement>(null), peer = useRef<RTCPeerConnection | null>(null), session = useRef(''), timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [state, setState] = useState('idle'), [message, setMessage] = useState('Video is receive-only. Sessions close after 30 seconds.');
  const stop = useCallback(async () => {
    if (timer.current) clearTimeout(timer.current);
    peer.current?.close(); peer.current = null;
    if (video.current) video.current.srcObject = null;
    const token = session.current; session.current = '';
    setState('idle');
    if (token) { try { await api(`/ring/devices/${encodeURIComponent(device.id)}/stream`, { method: 'DELETE', keepalive: true, body: JSON.stringify({ session: token }) }); setMessage('Live session closed.'); } catch (error) { setMessage(`Video stopped locally. Cleanup: ${(error as Error).message}`); } }
  }, [device.id]);
  useEffect(() => { const leave = () => { void stop(); }; window.addEventListener('pagehide', leave); return () => { window.removeEventListener('pagehide', leave); void stop(); }; }, [stop]);
  const start = async () => {
    setState('connecting'); setMessage('Connecting to the Ring device…');
    try {
      const pc = new RTCPeerConnection(); peer.current = pc;
      pc.addTransceiver('video', { direction: 'recvonly' });
      pc.ontrack = event => { if (video.current) video.current.srcObject = event.streams[0] || new MediaStream([event.track]); };
      pc.onconnectionstatechange = () => { if (pc.connectionState === 'connected') { setState('playing'); setMessage('Live Ring video · receive-only'); } else if (pc.connectionState === 'failed') { setMessage('The video connection failed. Try reconnecting.'); void stop(); } };
      await pc.setLocalDescription(await pc.createOffer());
      await new Promise<void>((resolve, reject) => { if (pc.iceGatheringState === 'complete') return resolve(); const timeout = setTimeout(() => reject(new Error('ICE gathering timed out.')), 10000); pc.onicegatheringstatechange = () => { if (pc.iceGatheringState === 'complete') { clearTimeout(timeout); resolve(); } }; });
      const result = await api(`/ring/devices/${encodeURIComponent(device.id)}/stream`, { method: 'POST', body: JSON.stringify({ offer: pc.localDescription?.sdp }) });
      session.current = result.session;
      await pc.setRemoteDescription({ type: 'answer', sdp: result.answer });
      timer.current = setTimeout(() => { void stop(); }, 30000);
    } catch (error) { await stop(); setMessage((error as Error).message); }
  };
  return <div className="live-view"><div className="video-frame"><video ref={video} autoPlay playsInline muted aria-label={`Live video from ${device.name}`} /><span className="video-label">{state === 'idle' ? 'Live view is stopped' : 'Ring live view'}</span></div><div className="video-controls"><p role="status">{message}</p><button className="button" disabled={device.status !== 'online'} onClick={() => state === 'idle' ? void start() : void stop()}>{state === 'idle' ? <><Play size={16} />Start live view</> : <><Stop size={16} />Stop</>}</button></div></div>;
}
