'use client';
import { useEffect, useState } from 'react';
import { Check, Clock, DoorOpen, ShieldCheck } from '@phosphor-icons/react';
import { Brand } from './Brand';
import { api } from './api';
export function Visitor() {
  const [token, setToken] = useState(''), [info, setInfo] = useState<any>(null), [status, setStatus] = useState<any>(null), [statusToken, setStatusToken] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  useEffect(() => { const token = new URLSearchParams(window.location.search).get('token') || ''; setToken(token); if (!token) { setError('Scan a current DoorSignal sign or ask your host for an invitation link.'); return; } const saved = sessionStorage.getItem(`ds-checkin:${token.slice(-24)}`); if (saved) setStatusToken(saved); api(`/checkin/info?token=${encodeURIComponent(token)}`).then(setInfo).catch(error => setError(error.message)); }, []);
  useEffect(() => { if (!statusToken) return; const poll = () => api(`/checkin/status?token=${encodeURIComponent(statusToken)}`).then(value => { setStatus(value); setError(''); }).catch(error => setError(error.message)); void poll(); const interval = setInterval(() => { if (!document.hidden) void poll(); }, 5000); return () => clearInterval(interval); }, [statusToken]);
  return <div className="visitor-shell"><header><a href="/" aria-label="DoorSignal home"><Brand /></a><span className="quiet">Visitor check-in</span></header><main id="main" className="visitor-card">{info?.mode === 'replay' && <span className="mode-badge replay"><span className="dot" />Demo replay · fictional visit</span>}{status ? <div className="visitor-status"><span className={`status-illustration ${status.status === 'acknowledged' || status.status === 'resolved' ? 'green' : ''}`}>{status.status === 'acknowledged' || status.status === 'resolved' ? <Check size={42} /> : <Clock size={42} weight="light" />}</span><p className="eyebrow">{info?.siteName || 'DoorSignal House'}</p><h1>{status.status === 'acknowledged' ? 'They’re on their way.' : status.status === 'resolved' ? 'All taken care of.' : 'You’re checked in.'}</h1><p>{status.message}</p><div className="visitor-receipt"><span>{status.name}</span><span className="badge acknowledged">Saved</span></div><small>This page updates when your host responds. You can leave it open.</small></div> : <><span className="visitor-door"><DoorOpen size={36} weight="light" /></span><p className="eyebrow">{info?.siteName || 'Welcome'}</p><h1>A good welcome<br />starts with hello.</h1><p>Tell us a little about your visit.<br />We’ll keep you updated right here.</p>{info && <form onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(''); try { const result = await api('/checkin', { method: 'POST', body: JSON.stringify({ token, name: form.get('name'), kind: form.get('kind'), consent: form.get('consent') === 'on' }) }); sessionStorage.setItem(`ds-checkin:${token.slice(-24)}`, result.token); setStatusToken(result.token); } catch (error) { setError((error as Error).message); } finally { setBusy(false); } }}><label>Your name<input name="name" autoComplete="name" placeholder="First and last name" required maxLength={80} /></label><label>What brings you here?<select name="kind"><option value="GUEST">I’m visiting someone</option><option value="DELIVERY">I’m making a delivery</option><option value="SERVICE">I’m here for a service visit</option><option value="UNMATCHED">Something else</option></select></label><label className="checkbox-label"><input type="checkbox" name="consent" required />I agree to share these details with the site’s hosts for this visit.</label><p className="small quiet">Check-in details expire after {info.retentionDays} {info.retentionDays === 1 ? 'day' : 'days'}. <a href="/privacy">Read about your data.</a></p><button className="button primary" disabled={busy}>{busy ? 'Saving your check-in…' : 'Let my host know'}<span aria-hidden="true">↗</span></button></form>}</>}{error && <p role="alert" className="alert error">{error}</p>}<div className="visitor-privacy"><ShieldCheck size={17} /><span>No facial recognition. No camera access required.</span></div></main><footer>DoorSignal · A clear handoff at the door.</footer></div>;
}
